version: "3"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.0
        environment:
            discovery.type: single-node
        ports:
            - "9200:9200"
        networks:
            - elastic
    kibana:
        image: docker.elastic.co/kibana/kibana-oss:6.6.0
        ports:
            - "5601:5601"
        networks:
            - elastic
        depends_on:
            - elasticsearch
networks:
    elastic:
